### ISSUE TITLE
[Bug]: Failed to sync

### ISSUE THREAD

**Issue by HernanLencinas** [RapidAPI/feedback#105]
### What happened?

Unable to retrieve projects from my account

["ERROR" - 2023-03-31T21:35:27.641Z - v1.10.1] 
  Error calling "/api/v3/teams/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["ERROR" - 2023-03-31T21:35:28.512Z - v1.10.1] 
  Error calling "/api/v3/projects/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["INFO" - 2023-03-31T21:41:51.482Z - v1.10.1] 

### Steps to reproduce?

1. Install extension rapidapi
2. Clic on Signin button. Redirect to rapidapi.com page and login with my account success.
3. Click on button "Create or open project"
4. On window "Project selection" show message "Failed to retrieve projects"

<img width="1483" alt="Screenshot 2023-03-31 at 18 44 36" src="https://user-images.githubusercontent.com/12104700/229238632-ca601408-247d-4139-8f4e-81da4c9cea31.png">

### VS Code version

1.77.0

### Extension version

1.10.1

### Relevant log output

```shell
["INFO" - 2023-03-31T21:31:09.404Z - v1.10.1] 
  Running on VS Code: 1.77.0 - Node.js: v16.14.2
["INFO" - 2023-03-31T21:31:09.406Z - v1.10.1] 
  Current theme in use: Hack The Box
["VERBOSE" - 2023-03-31T21:31:09.406Z - v1.10.1] 
  Number of requests performed: 31
["INFO" - 2023-03-31T21:31:11.141Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:11.783Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:11.792Z - v1.10.1] 
  [push-settings]: {"signedIn":true}
["INFO" - 2023-03-31T21:31:19.073Z - v1.10.1] 
  [request-updates]: no data provided
["INFO" - 2023-03-31T21:31:19.073Z - v1.10.1] 
  [push-settings]: {"signedIn":true}
["INFO" - 2023-03-31T21:31:19.083Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:19.083Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:19.106Z - v1.10.1] 
  Signed out
["INFO" - 2023-03-31T21:31:19.114Z - v1.10.1] 
  [request-updates]: no data provided
["INFO" - 2023-03-31T21:31:19.118Z - v1.10.1] 
  [push-settings]: {"signedIn":false}
["INFO" - 2023-03-31T21:31:19.120Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:19.120Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:35.580Z - v1.10.1] 
  Signed in
["INFO" - 2023-03-31T21:31:35.581Z - v1.10.1] 
  [request-updates]: no data provided
["INFO" - 2023-03-31T21:31:35.581Z - v1.10.1] 
  [push-settings]: {"signedIn":true}
["INFO" - 2023-03-31T21:31:35.591Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:35.592Z - v1.10.1] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-03-31T21:31:40.321Z - v1.10.1] 
  Open project selection...
["INFO" - 2023-03-31T21:31:40.322Z - v1.10.1] 
  START: Fetch RapidAPI projects...
["INFO" - 2023-03-31T21:31:40.323Z - v1.10.1] 
  END: Fetch RapidAPI projects...
["ERROR" - 2023-03-31T21:31:41.389Z - v1.10.1] 
  Error calling "/api/v3/teams/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["ERROR" - 2023-03-31T21:31:42.050Z - v1.10.1] 
  Error calling "/api/v3/projects/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["INFO" - 2023-03-31T21:32:09.323Z - v1.10.1] 
  Open project selection...
["INFO" - 2023-03-31T21:32:09.324Z - v1.10.1] 
  START: Fetch RapidAPI projects...
["INFO" - 2023-03-31T21:32:09.324Z - v1.10.1] 
  END: Fetch RapidAPI projects...
["ERROR" - 2023-03-31T21:32:10.248Z - v1.10.1] 
  Error calling "/api/v3/teams/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["ERROR" - 2023-03-31T21:32:10.905Z - v1.10.1] 
  Error calling "/api/v3/projects/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["INFO" - 2023-03-31T21:35:09.519Z - v1.10.1] 
  Open project selection...
["INFO" - 2023-03-31T21:35:09.520Z - v1.10.1] 
  START: Fetch RapidAPI projects...
["INFO" - 2023-03-31T21:35:09.521Z - v1.10.1] 
  END: Fetch RapidAPI projects...
["ERROR" - 2023-03-31T21:35:10.549Z - v1.10.1] 
  Error calling "/api/v3/teams/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["ERROR" - 2023-03-31T21:35:11.256Z - v1.10.1] 
  Error calling "/api/v3/projects/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["INFO" - 2023-03-31T21:35:26.970Z - v1.10.1] 
  Open project selection...
["INFO" - 2023-03-31T21:35:26.970Z - v1.10.1] 
  START: Fetch RapidAPI projects...
["INFO" - 2023-03-31T21:35:26.970Z - v1.10.1] 
  END: Fetch RapidAPI projects...
["ERROR" - 2023-03-31T21:35:27.641Z - v1.10.1] 
  Error calling "/api/v3/teams/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["ERROR" - 2023-03-31T21:35:28.512Z - v1.10.1] 
  Error calling "/api/v3/projects/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["INFO" - 2023-03-31T21:41:51.482Z - v1.10.1] 
  Open project selection...
["INFO" - 2023-03-31T21:41:51.483Z - v1.10.1] 
  START: Fetch RapidAPI projects...
["INFO" - 2023-03-31T21:41:51.483Z - v1.10.1] 
  END: Fetch RapidAPI projects...
["ERROR" - 2023-03-31T21:41:52.413Z - v1.10.1] 
  Error calling "/api/v3/teams/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["ERROR" - 2023-03-31T21:41:53.050Z - v1.10.1] 
  Error calling "/api/v3/projects/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["INFO" - 2023-03-31T21:44:22.257Z - v1.10.1] 
  Open project selection...
["INFO" - 2023-03-31T21:44:22.259Z - v1.10.1] 
  START: Fetch RapidAPI projects...
["INFO" - 2023-03-31T21:44:22.259Z - v1.10.1] 
  END: Fetch RapidAPI projects...
["ERROR" - 2023-03-31T21:44:23.008Z - v1.10.1] 
  Error calling "/api/v3/teams/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
["ERROR" - 2023-03-31T21:44:23.667Z - v1.10.1] 
  Error calling "/api/v3/projects/": 401 - Unauthorized - {"detail":{"message":"Authentication credentials were not provided.","error":"NotAuthenticated"}}
```

**Comment by princejohnsantillan** [comment]
I'm getting the same issue

**Comment by princejohnsantillan** [comment]
Looks like this issue started when the client started to depend on the "RapidAPI Services" extension. I downgraded to version 1.9.3 and it works,

**Comment by ststimac** [comment]
@princejohnsantillan @HernanLencinas thank you for reporting this, we're looking at this now.

**Comment by HernanLencinas** [comment]
> Looks like this issue started when the client started to depend on the "RapidAPI Services" extension. I downgraded to version 1.9.3 and it works,

Confirmed. Downgrade to version 1.9.3 worked for me too.

**Comment by estruyf** [comment]
When you install the latest version, was the RapidAPI Services extension installed? If so, what does the log of the RapidAPI Services extension look like?

**Comment by estruyf** [comment]
We've implemented a fix in version `1.10.2`. Can you verify if this fixes it as well on your end?

If not, could you share the logs from both the client and services extension, please?

**Comment by HernanLencinas** [comment]
The fix worked perfectly. Thank you very much for the help.

["INFO" - 2023-04-24T14:20:55.692Z - v1.10.2] 
  Running on VS Code: 1.77.3 - Node.js: v16.14.2
["INFO" - 2023-04-24T14:20:55.694Z - v1.10.2] 
  Current theme in use: Hack The Box
["VERBOSE" - 2023-04-24T14:20:55.694Z - v1.10.2] 
  Number of requests performed: 66
["INFO" - 2023-04-24T14:20:55.928Z - v1.10.2] 
  [update-project-title]: "Go Backend (online)"
["INFO" - 2023-04-24T14:20:56.814Z - v1.10.2] 
  [update-project-title]: "Go Backend (online)"
["INFO" - 2023-04-24T14:20:57.671Z - v1.10.2] 
  [push-settings]: {"signedIn":true}
["INFO" - 2023-04-24T14:20:59.222Z - v1.10.2] 
  EventStream connected
["INFO" - 2023-04-24T14:20:59.223Z - v1.10.2] 
  EventStream put
["INFO" - 2023-04-24T14:20:59.224Z - v1.10.2] 
  Open project selection...
["INFO" - 2023-04-24T14:20:59.231Z - v1.10.2] 
  START: Fetch RapidAPI projects...
["INFO" - 2023-04-24T14:20:59.231Z - v1.10.2] 
  END: Fetch RapidAPI projects...

**Comment by princejohnsantillan** [comment]
New version is working for me too. Thanks @estruyf

**Comment by estruyf** [comment]
Thanks @HernanLencinas and @princejohnsantillan for confirming 🙏

**Comment by princejohnsantillan** [comment]
@estruyf  with the new version though it always opens my browser to authenticate everytime I open my vscode.  It's pretty annoying. Looks like I'll have to use the older version again for now.

**Comment by estruyf** [comment]
Thank you @princejohnsantillan for the feedback, I can see that in our internal beta, we've implemented a fix for this issue, so will check how we can bring it as a patch release.

**Comment by princejohnsantillan** [comment]
That's awesome @estruyf ! Thanks for all your hard work!

**Comment by estruyf** [comment]
@princejohnsantillan would you be able to provide me the log output of the client and services extension? That way I can verify if we are talking about the same issue.

**Comment by princejohnsantillan** [comment]
I'd be happy to help but I'm not sure how to do that. Can you guide me how to get the log output please @estruyf?

**Comment by estruyf** [comment]
Sure, if you click on the `view` menu -> `output`. It opens the following view:

![Xnapper-2023-04-28-13 21 25](https://user-images.githubusercontent.com/2900833/235134731-7982fe57-f971-4fe3-bae4-bcf5a93d77c2.png)

From the dropdown, you can find `RapidAPI Client` and `RapidAPI Services`. There you can find the logs.

**Comment by princejohnsantillan** [comment]
@estruyf after re-installing the latest version, it wont let me log in.

Client:
["INFO" - 2023-04-28T11:37:34.655Z - v1.10.2] 
  Running on VS Code: 1.77.3 - Node.js: v16.14.2
["INFO" - 2023-04-28T11:37:34.656Z - v1.10.2] 
  Current theme in use: Default Dark+
["INFO" - 2023-04-28T11:37:40.355Z - v1.10.2] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-04-28T11:37:40.594Z - v1.10.2] 
  [update-project-title]: "Default (local)"
["INFO" - 2023-04-28T11:37:40.600Z - v1.10.2] 
  [push-settings]: {"signedIn":false}


Service:
["INFO" - 2023-04-28T11:37:34.583Z - v1.0.1]
  Authentication Provider registered
["INFO" - 2023-04-28T11:37:34.655Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:34.656Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:40.345Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:40.345Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:40.587Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:40.591Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:40.592Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:40.597Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:40.609Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:41.670Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:41.671Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:37:53.273Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:53.274Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:37:53.455Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:53.455Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:37:53.619Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:53.619Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:37:53.789Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:53.789Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:37:57.825Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:57.825Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:37:57.991Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:37:57.991Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:06.954Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:06.955Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:07.161Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:07.161Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:07.371Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:07.371Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:08.217Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:08.217Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:08.651Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:08.651Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:08.864Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:08.865Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:09.880Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:09.880Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:26.130Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:26.130Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:27.009Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:27.009Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:27.192Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:27.193Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:27.386Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:27.387Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:27.822Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:27.822Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:28.003Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:28.003Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:28.184Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:28.184Z - v1.0.1]
  authenticate command called
["INFO" - 2023-04-28T11:38:49.925Z - v1.0.1]
  getSession command called
["INFO" - 2023-04-28T11:38:49.925Z - v1.0.1]
  authenticate command called
  
  
  Everytime I click the Sign In Icon it sayas authenticate command called but does nothing

**Comment by estruyf** [comment]
A new services version 1.0.2 is being published, that should fix the authentication issue. Let me know if this fixes the issue once you were able to install the new version.

**Comment by Jijilian** [comment]
> We've implemented a fix in version `1.10.2`. Can you verify if this fixes it as well on your end?
> 
> If not, could you share the logs from both the client and services extension, please?

Hello! The fix doesn't work for me! I still have the problem!

**Comment by estruyf** [comment]
Thanks @Jijilian - we just had a meeting around this issue. It seems unrelated to the extension but somewhere internally in a verification process. We are working on a fix and will let you know when it has been implemented.

**Comment by estruyf** [comment]
@Jijilian @princejohnsantillan would you be able to go to: https://paw.cloud/account/login and login from there? Once you logged in, please try it again in Visual Studio Code.

**Comment by princejohnsantillan** [comment]
@estruyf  I was able to login with the new version. Thanks!
